### ISSUE TITLE
配置与i18n索引跳转支持

### ISSUE THREAD

**Issue by shuqingzai** [oldme-git/GoFrame-Helper#17]
目前插件`v1.0.3`已支持 i18n 的key写入自动补全，但是点击key时，无法跳转的实现文件，希望可以支持
![image](https://github.com/oldme-git/GoFrame-Helper/assets/44406033/cec23cf0-df75-4ed5-b465-c22632cd2faf)
点击跳转时，不支持
![image](https://github.com/oldme-git/GoFrame-Helper/assets/44406033/d5fa388c-77c8-49e1-a3c8-f06ad035ad3a)

希望可以支持双向点击跳转
- 在i18n翻译文件中点击key可以找到使用的地方
- 在调用 `g.i18n.T()` 时，点击对应的key可以找到对应的实现，多个翻译实现时，列出列表
参考：laravel idea
![image](https://github.com/oldme-git/GoFrame-Helper/assets/44406033/695198b2-ecef-464f-84c4-de800924b76a)

![image](https://github.com/oldme-git/GoFrame-Helper/assets/44406033/e19e86bc-edba-417b-99b2-db541a426b9f)

**Comment by oldme-git** [comment]
@shuqingzai 你好，go 跳转配置文件已经实现了，配置文件跳转没有那么容易，lv idea因为都是php文件，所以容易处理，gf是多配置文件，预计只做单向跳转
