### ISSUE TITLE
字段名 bug

### ISSUE THREAD

**Issue by Q32611600** [oldme-git/GoFrame-Helper#24]
![1731892373925](https://github.com/user-attachments/assets/4842e36f-c27b-4f26-8650-e7a5d5746cbf)

1. 字段不是按实际的字段名获取的，实际的字段名是roomNo,
2. 新版本的gf 服务代码变更为func New() service.IRoom {
	return &sRoom{}
}

与目前生成的不一致

**Comment by oldme-git** [comment]
@Q32611600 插件生成代码是依赖`gf-cli`的，这一块应该没问题
