### ISSUE TITLE
支持API自定义规则提示与I18N文本提示

### ISSUE THREAD

**Issue by shuqingzai** [oldme-git/GoFrame-Helper#7]
1. 自定义验证规则的提示，目前在编写API请求文件时，已经支持 GF 内置验证规则的提示，但是未支持用户自定义规则的提示
    
![20231230-101243](https://github.com/oldme-git/GoFrame-Helper/assets/44406033/888799e5-7477-48c4-a3dd-456fd2809d9c)

2. 在使用 `g.I18n().T(ctx, "user.account.format.wrong_or_empty")` 翻译时， key( `user.account.format.wrong_or_empty` ) 未能提示，在 manifest/i18n 或 resource/i18n 存放大量的国际化翻译文件，希望可以支持 key 的提示，类似 Laravel Idea

**Comment by oldme-git** [comment]
@shuqingzai 
i18n的功能可以增加。
gvaild的自定义规则不太好弄，因为gf的全局自定义规则的注册位置没有具体的规范，不太好获取原始数据。

**Comment by shuqingzai** [comment]
> @shuqingzai i18n的功能可以增加。 gvaild的自定义规则不太好弄，因为gf的全局自定义规则的注册位置没有具体的规范，不太好获取原始数据。

@oldme-git 应该可以根据注册进去的 map 找到原始值？[全局校验规则注册](https://goframe.org/pages/viewpage.action?pageId=7302163#id-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A7%84%E5%88%99%E8%A7%84%E5%88%99%E6%B3%A8%E5%86%8C-%E5%85%A8%E5%B1%80%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99%E6%B3%A8%E5%86%8C)

**Comment by oldme-git** [comment]
@shuqingzai 这个功能复杂度太高，如果非要自定义规则，或许在设置中加入一个文本框，手动填进去规则更好

**Comment by shuqingzai** [comment]
> @shuqingzai 这个功能复杂度太高，如果非要自定义规则，或许在设置中加入一个文本框，手动填进去规则更好

😄 这样团队就不能共享了

**Comment by oldme-git** [comment]
@shuqingzai 确实，我想想这个问题，如果有解决方案，我会在下个版本中加入
