### ISSUE TITLE
[BUG] 每次保存文件时，都提示 CLI 工具没有

### ISSUE THREAD

**Issue by shuqingzai** [oldme-git/GoFrame-Helper#9]
1. 我已经安装了 GF 的 CLI 工具，但是每次保存文件都提示下面这个
<img width="436" alt="image" src="https://github.com/oldme-git/GoFrame-Helper/assets/44406033/0ac9da76-f017-41c3-9d12-bda83ab2b88a">

2. 希望把这些可配置项可让用户自行配置是否启用检测

**Comment by oldme-git** [comment]
@shuqingzai 在setting-tools-GoFrame Helper中关闭ctrl和controller的自动监听，下个版本如果监测gf工具不可用，会自动关闭监听。另外你安装了gf-cli，在控制台输入gf -v会是信息吗，系统是什么

**Comment by shuqingzai** [comment]
> gf -v

@oldme-git 

1. OS
```bash
# name -v
Darwin Kernel Version 22.6.0: Tue Nov  7 21:40:08 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_ARM64_T6000
```

2. GF Version
```bash
╰─⠠⠵ gf -v
v2.6.1
Welcome to GoFrame!
Env Detail:
  Go Version: go1.21.5 darwin/arm64
  GF Version(go.mod):
    github.com/gogf/gf/contrib/drivers/mysql/v2@v2.6.1
    github.com/gogf/gf/v2@v2.6.1
CLI Detail:
  Installed At: /Code/Go/bin/gf
  Built Go Version: go1.21.5
  Built GF Version: v2.6.1
Others Detail:
  Docs: https://goframe.org
  Now : 2023-12-31T22:07:18+08:00
```

**Comment by shuqingzai** [comment]
@oldme-git 似乎是 CLI 路径问题？插件没有正确读取路径位置，如果我设置为绝对路径，就没有问题，在 Mac 中 gf 命令冲突，需要设置别名，但是插件似乎没有正确读取，参考：[快速开始-Mac环境](https://goframe.org/pages/viewpage.action?pageId=1114399#id-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B-Mac%E7%8E%AF%E5%A2%83)

```bash
#╰─⠠⠵ where gf
gf: aliased to gf
/XXX/Code/Go/bin/gf
```

<img width="487" alt="image" src="https://github.com/oldme-git/GoFrame-Helper/assets/44406033/d27114c7-99a9-4d6e-9bfc-5c0739c372e8">

**Comment by oldme-git** [comment]
@shuqingzai 方便留个邮箱或者微信吗，我需要用MacOS测试一下，可以发到我的邮箱: tyyn1022@gmail.com. 感谢

**Comment by shuqingzai** [comment]
> @shuqingzai 方便留个邮箱或者微信吗，我需要用MacOS测试一下，可以发到我的邮箱: [tyyn1022@gmail.com](mailto:tyyn1022@gmail.com). 感谢

推给你了 @oldme-git

**Comment by shuqingzai** [comment]
> @shuqingzai 方便留个邮箱或者微信吗，我需要用MacOS测试一下，可以发到我的邮箱: [tyyn1022@gmail.com](mailto:tyyn1022@gmail.com). 感谢

其实使用 Linux 应该也可以测试吧？设置个别名应该就会有问题，我不确定~
